"""Principal Agent — acts as a principal/lead engineer for the repository.

Performs architecture reviews on large PRs, generates PRDs for labeled issues,
and decomposes large refactoring efforts into ordered PR-sized steps.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

from caretaker.agent_protocol import AgentResult, BaseAgent

if TYPE_CHECKING:
    from caretaker.state.models import OrchestratorState, RunSummary

logger = logging.getLogger(__name__)


class PrincipalAgent(BaseAgent):
    """Principal/lead engineer agent for architecture, design, and planning."""

    @property
    def name(self) -> str:
        return "principal"

    def enabled(self) -> bool:
        return self._ctx.config.principal_agent.enabled

    async def execute(
        self,
        state: OrchestratorState,
        event_payload: dict[str, Any] | None = None,
    ) -> AgentResult:
        cfg = self._ctx.config.principal_agent
        llm = self._ctx.llm_router
        github = self._ctx.github
        owner = self._ctx.owner
        repo = self._ctx.repo

        reviews = 0
        prds = 0
        refactors = 0
        errors: list[str] = []

        # ── Architecture review on large PRs ────────────────────────
        if cfg.auto_review_large_prs:
            try:
                prs = await github.list_pull_requests(owner, repo, state="open")
                for pr in prs:
                    if pr.draft:
                        continue
                    # Check if PR is large enough to warrant architecture review
                    pr_detail = await github.get_pull_request(owner, repo, pr.number)
                    if pr_detail is None:
                        continue

                    # Use the PR body length + title as a proxy for size
                    # In production, you'd check additions/deletions from the API
                    body_len = len(pr_detail.body or "")
                    if body_len < cfg.large_pr_threshold:
                        continue

                    if not llm or not llm.available:
                        logger.info(
                            "Skipping architecture review for PR #%d — LLM not available",
                            pr.number,
                        )
                        continue

                    logger.info("Running architecture review for PR #%d", pr.number)
                    diff_context = f"PR #{pr.number}: {pr.title}\n\n{pr_detail.body or ''}"
                    analysis = await llm.claude.analyze_architecture(
                        diff_context,
                        repo_context=f"{owner}/{repo}",
                    )

                    if analysis:
                        comment_body = (
                            "## 🏗️ Architecture Review\n\n"
                            f"*Automated review by caretaker principal agent*\n\n"
                            f"{analysis}"
                        )
                        await github.add_issue_comment(owner, repo, pr.number, comment_body)
                        reviews += 1
                        logger.info("Posted architecture review for PR #%d", pr.number)
            except Exception as exc:
                logger.error("Architecture review failed: %s", exc, exc_info=True)
                errors.append(f"architecture_review: {exc}")

        # ── PRD generation for labeled issues ───────────────────────
        try:
            issues = await github.list_issues(owner, repo, state="open")
            for issue in issues:
                issue_labels = {lbl.name for lbl in issue.labels}
                if not issue_labels.intersection(cfg.prd_labels):
                    continue

                if not llm or not llm.available:
                    logger.info(
                        "Skipping PRD generation for issue #%d — LLM not available",
                        issue.number,
                    )
                    continue

                logger.info("Generating PRD for issue #%d", issue.number)
                prd_text = await llm.claude.create_prd(
                    issue.body or issue.title,
                    repo_context=f"{owner}/{repo}",
                )

                if prd_text:
                    comment_body = (
                        "## 📋 Product Requirements Document\n\n"
                        f"*Generated by caretaker principal agent*\n\n"
                        f"{prd_text}"
                    )
                    await github.add_issue_comment(owner, repo, issue.number, comment_body)
                    prds += 1
                    logger.info("Posted PRD for issue #%d", issue.number)
        except Exception as exc:
            logger.error("PRD generation failed: %s", exc, exc_info=True)
            errors.append(f"prd_generation: {exc}")

        return AgentResult(
            processed=reviews + prds + refactors,
            errors=errors,
            extra={
                "reviews": reviews,
                "prds_created": prds,
                "refactors_planned": refactors,
            },
        )

    def apply_summary(self, result: AgentResult, summary: RunSummary) -> None:
        summary.principal_reviews = result.extra.get("reviews", 0)
        summary.principal_prds_created = result.extra.get("prds_created", 0)
        summary.principal_refactors_planned = result.extra.get("refactors_planned", 0)
