"""Migration Agent — manages framework/language version migrations.

Scans for deprecated API usage, creates migration plans, and can execute
simple API replacements via the Foundry executor.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

from caretaker.agent_protocol import AgentResult, BaseAgent

if TYPE_CHECKING:
    from caretaker.state.models import OrchestratorState, RunSummary

logger = logging.getLogger(__name__)


class MigrationAgent(BaseAgent):
    """Framework/language migration management agent."""

    @property
    def name(self) -> str:
        return "migration"

    def enabled(self) -> bool:
        return self._ctx.config.migration_agent.enabled

    async def execute(
        self,
        state: OrchestratorState,
        event_payload: dict[str, Any] | None = None,
    ) -> AgentResult:
        cfg = self._ctx.config.migration_agent
        llm = self._ctx.llm_router
        github = self._ctx.github
        owner = self._ctx.owner
        repo = self._ctx.repo

        deprecations_found = 0
        fixes_applied = 0
        errors: list[str] = []

        if not cfg.target_migrations:
            logger.info("No target migrations configured — skipping")
            return AgentResult(processed=0, errors=errors)

        if not llm or not llm.available:
            logger.info("Skipping migration analysis — LLM not available")
            return AgentResult(processed=0, errors=errors)

        # ── Analyze codebase for deprecated API usage ───────────────
        for migration in cfg.target_migrations:
            target_name = migration.get("name", "unknown")
            target_version = migration.get("version", "")

            try:
                logger.info(
                    "Scanning for deprecated APIs: %s %s",
                    target_name,
                    target_version,
                )

                # Use repo info as context for the migration analysis
                repo_info = await github.get_repo(owner, repo)
                repo_context = (
                    f"Repository: {owner}/{repo}\n"
                    f"Default branch: {repo_info.default_branch}\n"
                    f"Migration: {target_name} to {target_version}"
                )

                analysis = await llm.claude.analyze_migration(
                    repo_context,
                    target=f"{target_name} {target_version}",
                )

                if analysis:
                    deprecations_found += 1

                    # Create a migration plan
                    plan = await llm.claude.plan_migration(
                        analysis,
                        target=f"{target_name} {target_version}",
                    )

                    if plan:
                        # Create an issue with the migration plan
                        issue_body = (
                            f"## Migration Plan: {target_name} {target_version}\n\n"
                            f"*Generated by caretaker migration agent*\n\n"
                            f"### Deprecated API Usage\n\n{analysis}\n\n"
                            f"### Migration Steps\n\n{plan}"
                        )
                        await github.create_issue(
                            owner,
                            repo,
                            title=f"migration: {target_name} {target_version}",
                            body=issue_body,
                            labels=["migration", "caretaker"],
                        )
                        logger.info(
                            "Created migration issue for %s %s",
                            target_name,
                            target_version,
                        )

            except Exception as exc:
                logger.error(
                    "Migration analysis failed for %s: %s",
                    target_name,
                    exc,
                    exc_info=True,
                )
                errors.append(f"migration_{target_name}: {exc}")

        return AgentResult(
            processed=deprecations_found,
            errors=errors,
            extra={
                "deprecations_found": deprecations_found,
                "fixes_applied": fixes_applied,
            },
        )

    def apply_summary(self, result: AgentResult, summary: RunSummary) -> None:
        summary.migration_deprecations_found = result.extra.get("deprecations_found", 0)
        summary.migration_fixes_applied = result.extra.get("fixes_applied", 0)
