"""Models and scorecard schemas for the Review Agent."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class TargetInfo(BaseModel):
    kind: Literal["pull_request", "issue", "run", "batch"]
    number: int | None = None
    title: str | None = None
    url: str | None = None


class WindowInfo(BaseModel):
    lookback_runs: int
    lookback_days: int


class OverallScore(BaseModel):
    score: int
    grade: str
    confidence: float
    status: str


class DimensionScore(BaseModel):
    score: int
    weight: float
    notes: list[str] = Field(default_factory=list)


class ReviewDimensions(BaseModel):
    outcome: DimensionScore
    execution: DimensionScore
    reliability: DimensionScore
    maintainability: DimensionScore
    communication: DimensionScore


class Findings(BaseModel):
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    recurring_issues: list[str] = Field(default_factory=list)
    anomalies: list[str] = Field(default_factory=list)


class Retrospective(BaseModel):
    went_well: list[str] = Field(default_factory=list)
    failed: list[str] = Field(default_factory=list)
    do_better: list[str] = Field(default_factory=list)
    stop_or_less: list[str] = Field(default_factory=list)


class EvidenceCounters(BaseModel):
    run_summaries_considered: int = 0
    memory_entries_considered: int = 0
    tracker_signals: list[str] = Field(default_factory=list)
    github_comments_considered: int = 0


class OutputManifest(BaseModel):
    markdown_report_path: str | None = None
    json_report_path: str | None = None
    summary_comment_posted: bool = False


class ReviewScorecard(BaseModel):
    """The complete evaluation generated by the ReviewAgent."""

    model_config = ConfigDict(extra="allow")

    schema_version: Literal["v1"] = "v1"
    agent: Literal["review"] = "review"
    reviewed_at: datetime
    target: TargetInfo
    window: WindowInfo
    overall: OverallScore
    dimensions: ReviewDimensions
    findings: Findings
    retro: Retrospective
    evidence: EvidenceCounters
    outputs: OutputManifest


class ReviewRequest(BaseModel):
    """Internal model for explicit review requests."""

    target_kind: Literal["run", "issue", "pull_request", "batch"]
    target_number: int | None = None
    target_run_at: datetime | None = None
    lookback_runs: int = 10
    lookback_days: int = 30
    include_comments: bool = True
    include_memory: bool = True
    publish_summary_comment: bool = False


class ReviewReport(BaseModel):
    """Internal summary output returned by ReviewAgent.run()"""

    reviews_completed: int = 0
    artifacts_written: int = 0
    summary_comment_targets: int = 0
    average_score: float = 0.0
    critical_findings: list[str] = Field(default_factory=list)
    trend_flags: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
