apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: caretaker-virtualservice
  namespace: default
spec:
  hosts:
    - caretaker.cat-herding.net
  gateways:
    - aks-istio-ingress/cat-herding-gateway
  http:
    - route:
        - destination:
            host: caretaker-mcp.caretaker.svc.cluster.local
            port:
              number: 80
