"""Test Agent — monitors test coverage and quality.

Analyzes PRs for missing test coverage, detects flaky tests from CI history,
and generates test skeleton code via the Foundry executor.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

from caretaker.agent_protocol import AgentResult, BaseAgent

if TYPE_CHECKING:
    from caretaker.state.models import OrchestratorState, RunSummary

logger = logging.getLogger(__name__)


class TestAgent(BaseAgent):
    """Test coverage and quality agent."""

    @property
    def name(self) -> str:
        return "test"

    def enabled(self) -> bool:
        return self._ctx.config.test_agent.enabled

    async def execute(
        self,
        state: OrchestratorState,
        event_payload: dict[str, Any] | None = None,
    ) -> AgentResult:
        cfg = self._ctx.config.test_agent
        llm = self._ctx.llm_router
        github = self._ctx.github
        owner = self._ctx.owner
        repo = self._ctx.repo

        prs_analyzed = 0
        skeletons_generated = 0
        flaky_detected = 0
        errors: list[str] = []

        # ── Analyze open PRs for test coverage gaps ─────────────────
        try:
            prs = await github.list_pull_requests(owner, repo, state="open")
            for pr in prs:
                if pr.draft:
                    continue

                if not llm or not llm.available:
                    logger.info(
                        "Skipping test analysis for PR #%d — LLM not available",
                        pr.number,
                    )
                    continue

                pr_detail = await github.get_pull_request(owner, repo, pr.number)
                if pr_detail is None:
                    continue

                diff_context = f"PR #{pr.number}: {pr.title}\n\n{pr_detail.body or ''}"

                logger.info("Analyzing test coverage for PR #%d", pr.number)
                analysis = await llm.claude.analyze_test_coverage(diff_context)

                if analysis:
                    comment_body = (
                        "## 🧪 Test Coverage Analysis\n\n"
                        f"*Automated analysis by caretaker test agent*\n\n"
                        f"{analysis}"
                    )
                    await github.add_issue_comment(owner, repo, pr.number, comment_body)
                    prs_analyzed += 1
                    logger.info("Posted test coverage analysis for PR #%d", pr.number)

                    # Generate test skeletons if enabled
                    if cfg.generate_skeletons and skeletons_generated < cfg.max_skeletons_per_run:
                        skeleton = await llm.claude.generate_test_skeleton(
                            diff_context,
                            context=f"PR #{pr.number} in {owner}/{repo}",
                        )
                        if skeleton:
                            skeleton_comment = (
                                "## 🧪 Suggested Test Skeleton\n\n"
                                f"*Generated by caretaker test agent*\n\n"
                                f"```python\n{skeleton}\n```"
                            )
                            await github.add_issue_comment(owner, repo, pr.number, skeleton_comment)
                            skeletons_generated += 1

        except Exception as exc:
            logger.error("Test coverage analysis failed: %s", exc, exc_info=True)
            errors.append(f"test_coverage: {exc}")

        return AgentResult(
            processed=prs_analyzed,
            errors=errors,
            extra={
                "prs_analyzed": prs_analyzed,
                "skeletons_generated": skeletons_generated,
                "flaky_detected": flaky_detected,
            },
        )

    def apply_summary(self, result: AgentResult, summary: RunSummary) -> None:
        summary.test_prs_analyzed = result.extra.get("prs_analyzed", 0)
        summary.test_skeletons_generated = result.extra.get("skeletons_generated", 0)
        summary.test_flaky_detected = result.extra.get("flaky_detected", 0)
